# Copyright 2021, 2022, 2023, 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Set up Bazel workspace
description: Install necessary dependencies and load remote caches

outputs:
  repository-cache:
    description: Bazel repository cache directory
    value: ${{runner.temp}}/bazel-repository-cache
  action-cache:
    description: Bazel action cache directory
    value: ${{runner.temp}}/bazel-action-cache

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install APT packages
      shell: bash
      run: sudo apt-get update && sudo apt-get install libxml2-utils
      if: runner.os == 'Linux'
    - name: Install Homebrew packages
      # The Protocol Buffer rules need ‘realpath’ from the GNU coreutils.
      shell: bash
      run: brew update && brew install coreutils
      if: runner.os == 'macOS'
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: false
        release: false
        # See nt/INSTALL.W64 for the list of required MSYS2 packages
        install: >
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-xpm-nox
      if: runner.os == 'Windows'
    - name: Set up MSYS2 environment
      # Make Bazel find the right binaries on GitHub.  See
      # https://bazel.build/install/windows#bazel_does_not_find_bash_or_bashexe.
      shell: cmd
      run: |
        ECHO BAZEL_SH=C:\MSYS64\usr\bin\bash.exe>> %GITHUB_ENV%
      if: runner.os == 'Windows'
    - name: Cache Bazel repositories
      uses: actions/cache@v4
      with:
        path: ${{runner.temp}}/bazel-repository-cache
        key: bazel-repositories-${{hashFiles('**/WORKSPACE', '**.bzl')}}
        restore-keys: |
          bazel-repositories-
    - name: Cache Bazel results
      uses: actions/cache@v4
      with:
        path: ${{runner.temp}}/bazel-action-cache
        key: bazel-actions-${{runner.os}}-${{matrix.bazel}}-${{hashFiles('**')}}
        restore-keys: |
          bazel-actions-${{runner.os}}-${{matrix.bazel}}-
          bazel-actions-${{runner.os}}-
    - name: Set up .bazelrc
      shell: bash
      run: |
        cat >> github.bazelrc <<'EOF'
        common --announce_rc
        common --verbose_failures
        common --experimental_convenience_symlinks=ignore
        common --show_progress_rate_limit=10
        common --show_result=0
        common --nostamp
        test --test_output=errors
        EOF
