# Copyright 2021-2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Set up Bazel workspace
description: Install necessary dependencies and load remote caches

inputs:
  bazel-version:
    description: Bazel version to use
    required: false
    default: default
  cc:
    description: C/C++ compiler to use
    required: false
    default: >-
      ${{
      runner.os == 'Linux' && 'gcc'
      || (runner.os == 'macOS' && 'clang' || 'msvc')
      }}

runs:
  using: composite
  steps:
    - name: Set up Bazel
      uses: bazel-contrib/setup-bazel@0.18.0
      with:
        # The lockfile format differs between the Bazel versions, so only for
        # one version --lockfile_mode=error can work.  --lockfile_mode=update
        # would be useless since we never use the updated lockfiles, so switch
        # lockfiles off entirely in other Bazel versions.
        # --incompatible_enforce_starlark_utf8 was added in Bazel 8.1.
        # FIXME: Add it to the project’s .bazelrc once we drop support for
        # Bazel 8.0 and below.
        # See https://bazel.build/configure/windows#clang for how to configure
        # Bazel to use Clang on Windows.
        bazelrc: |
          common --announce_rc
          common --show_progress_rate_limit=10
          common --remote_download_minimal
          common --incompatible_config_setting_private_default_visibility
          common --experimental_ui_max_stdouterr_bytes=2000000
          common --lockfile_mode=${{inputs.bazel-version == 'default' && 'error' || 'off'}}
          build --verbose_failures
          build --experimental_convenience_symlinks=ignore
          build --show_result=0
          build --nostamp
          build --experimental_repository_cache_hardlinks
          build --incompatible_strict_action_env
          test --test_output=errors
          ${{
            inputs.bazel-version == 'default' &&
            'common --incompatible_enforce_starlark_utf8=error' || ''
          }}
          ${{
            runner.os == 'macOS' && inputs.cc == 'gcc' &&
            'common --config=macos-gcc' || ''
          }}
          ${{
            runner.os == 'Windows' && inputs.cc == 'clang' &&
            'build --config=clang-cl' || ''
          }}
        # Use disk cache to speed up runs.
        disk-cache: ${{inputs.bazel-version}}-${{inputs.cc}}
        repository-cache: true
    - id: msys2
      name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: false
        release: false
        install: >
          texinfo
      if: runner.os == 'Windows'
    - name: Set up Ubuntu worker
      shell: bash
      # We need to free up some disk space on the Ubuntu runners,
      # cf. https://github.com/actions/runner-images/issues/13189.
      # FIXME: Remove the cleanup steps once
      # https://github.com/actions/runner-images/issues/13189 or
      # https://github.com/actions/runner-images/issues/12721 are fixed.
      run: |
        set -x
        sudo apt-get update
        sudo apt-get remove \
          firefox google-chrome-stable microsoft-edge-stable \
          azure-cli google-cloud-cli google-cloud-cli-anthoscli \
          llvm-{16..18}-dev
        sudo apt-get install libxml2-utils libncurses-dev
        sudo apt-get autoremove
        sudo apt-get clean
        rm -r -f /usr/share/dotnet /usr/share/swift /usr/local/graalvm
        echo 'CC=${{matrix.cc}}' >> "${GITHUB_ENV:?}"
      if: runner.os == 'Linux'
    - name: Set up macOS worker
      shell: bash
      run: |
        brew update && brew install texinfo
        # Detect Xcode command-line tools on macOS to work around
        # https://github.com/bazelbuild/bazel/issues/14970.
        cov="$(xcrun --find llvm-cov)"
        echo "BAZEL_LLVM_COV=${cov:?}" >> "${GITHUB_ENV:?}"
        profdata="$(xcrun --find llvm-profdata)"
        echo "BAZEL_LLVM_PROFDATA=${profdata:?}" >> "${GITHUB_ENV:?}"
        if [ '${{matrix.cc}}' = gcc ]; then
          # “gcc” points to Clang on macOS.
          echo 'CC=gcc-14' >> "${GITHUB_ENV:?}"
        fi
      if: runner.os == 'macOS'
    - name: Set up Windows worker
      # Make Bazel find the right binaries on GitHub.  See
      # https://bazel.build/install/windows#bazel_does_not_find_bash_or_bashexe.
      shell: pwsh
      run: >-
        Add-Content
        -Verbose
        -LiteralPath $Env:GITHUB_ENV
        -Value 'BAZEL_SH=${{steps.msys2.outputs.msys2-location}}\usr\bin\bash.exe'
      if: runner.os == 'Windows'
    - name: Configure system
      shell: pwsh
      run: |
        $PSNativeCommandUseErrorActionPreference = $true
        $BazelVersion = '${{inputs.bazel-version}}'
        if ($BazelVersion -ne 'default') {
            Add-Content -Verbose -LiteralPath $Env:GITHUB_ENV -Value @(
                "USE_BAZEL_VERSION=$BazelVersion"
            )
        }
        # If we don’t have consistent line endings across the operating systems,
        # the MODULE.bazel.lock hashes will diverge for external repositories
        # using git_override.
        git config --global core.autocrlf false
        git config --global core.eol lf
