#!/bin/bash

# Copyright 2020, 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -u

# We don’t want any Go rules in the public packages, as our users would have to
# depend on the Go rules then as well.
echo 'Looking for unwanted Go targets in public packages'
grep --fixed-strings --regexp='@io_bazel_rules_go' \
  --line-number --context=3 --color=auto --recursive -- elisp emacs
# Check explicitly for exit status 1, to detect grep errors.
if (($? != 1)); then
  echo 'Unwanted Go targets found'
  exit 1
fi

bazel test //... || exit

case "$(uname -ms)" in
  'Darwin arm64') versions=(27.2) ;;
  *) versions=(26.{1,2,3} 27.{1,2}) ;;
esac

# Test versioned toolchains.
for version in "${versions[@]}"; do
  bazel test --extra_toolchains="//elisp:emacs_${version:?}_toolchain" //... || exit
done
