#!/bin/sh

# Copyright 2024, 2025, 2026 Philipp Stephani
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euC

workflow=update-lockfiles.yaml
run=lock.run

if [ -f "${run:?}" ]; then
  read -r id < "${run:?}"
else
  branch="$(git branch --show-current)"
  url="$(gh workflow run "${workflow:?}" --ref="${branch:?}")"
  id="${url##*/}"
  echo "${id:?}" > "${run:?}"
fi

gh run watch "${id:?}" --exit-status
gh run download "${id:?}"

for dir in . examples/ext; do
  out="${dir:?}/MODULE.bazel.lock"
  linux="lockfiles-Linux-X64/${out:?}"
  macos="lockfiles-macOS-ARM64/${out:?}"
  windows="lockfiles-Windows-X64/${out:?}"
  bazel run \
    --lockfile_mode=off \
    --norun_validations \
    -- \
    @phst_merge_bazel_lockfiles//:merge \
    --linux-amd64="${linux:?}" \
    --darwin-arm64="${macos:?}" \
    --windows-amd64="${windows:?}" \
    --local="${out:?}" \
    --output="${out:?}"
  rm -- "${linux:?}" "${macos:?}" "${windows:?}"
done

# This will fail if we forgot some OS above.
rmdir -- \
  lockfiles-*/examples/ext \
  lockfiles-*/examples \
  lockfiles-*

rm -- "${run:?}"
