#!/bin/bash

# Copyright 2024 Philipp Stephani
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

workflow=update-lockfiles.yaml
branch="$(git branch --show-current)"
now="$(date -u -Iseconds)"

gh workflow run "${workflow:?}" --ref="${branch:?}"

fetch_run_id() {
  gh run list \
    --workflow="${workflow:?}" \
    --event=workflow_dispatch \
    --branch="${branch:?}" \
    --created=">=${now:?}" \
    --limit=1 \
    --json=databaseId \
    --jq='.[].databaseId'
}

while id="$(fetch_run_id)" && [[ -z "${id}" ]]; do
  sleep 1
done

gh run watch "${id:?}"

dir="$(mktemp -d)"
gh run download "${id:?}" --dir="${dir:?}" --name=lockfiles
cp -R -i -v -- "${dir:?}/" ./
rm -r -- "${dir:?}"
