Defines the rule ~emacs_binary~, which compiles Emacs for use in Bazel.

* ~emacs_binary~ rule

Builds Emacs from a source repository.
The resulting executable can be used to run the compiled Emacs.

** ~name~ attribute

A unique name for this target.
Mandatory.

- Type :: name

** ~builtin_features~ attribute

Label for a file into which to write the list
of builtin features.  If not provided, don’t write such a file.
This is used by Gazelle.
Optional.

- Type :: output file

** ~dump_mode~ attribute

Dumping mode that Emacs will use.  This can be either
 ~portable~ to use the portable dumper introduced in Emacs 27, or ~unexec~ to
use the legacy “unexec” dumper.  Starting with Emacs 27, ~portable~ is strongly
recommended.
Optional.

- Type :: string
- Default :: ~"portable"~

** ~module_header~ attribute

Label for a file target that will receive the
~emacs-module.h~ header.  If not provided, don’t install the header.
Optional.

- Type :: output file

** ~readme~ attribute

The README file in the root of the Emacs repository.
This is necessary to determine the source root directory.
Mandatory.

- Type :: label

** ~srcs~ attribute

All Emacs source files.
Mandatory.

- Type :: list of labels

