# Copyright 2026 Philipp Stephani
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish to BCR

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
      release_run_id:
        type: string
        required: true

permissions:
  contents: read

jobs:
  publish:
    name: Publish to BCR
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.4.2
    with:
      tag_name: ${{inputs.tag}}
      registry_fork: phst/bazel-central-registry
      attest: true
      release_artifacts_run_id: ${{inputs.release_run_id}}
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets:
      publish_token: ${{secrets.BCR_PUBLISH_TOKEN}}
