# Copyright 2026 Philipp Stephani
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  create:
    name: Create release
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.7.0
    with:
      release_files: rules_elisp-*.tar.gz
      bazel_test_command: |-
        sudo apt-get install libxml2-utils libncurses-dev && bazel test //...
      prerelease: false
      draft: true
  bcr:
    name: Publish to BCR
    needs: create
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.4.2
    with:
      tag_name: ${{github.ref_name}}
      registry_fork: phst/bazel-central-registry
      attest: true
    secrets:
      publish_token: ${{secrets.BCR_PUBLISH_TOKEN}}
  publish:
    name: Publish release
    needs: bcr
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
